In [44]:
import os
import sys
parent_dir = os.path.abspath(os.path.join(os.path.join(os.getcwd(), ".."), ".."))
sys.path.append(parent_dir)

In [ ]:
import numpy as np
from data_generation.models.tech_substitution import TechnologySubstitution, TechSubNumericalSolver
from data_generation.models.general_ode_solver import FitzHughNagumoModel
from data_generation.models.general_ode_solver import GeneralODENumericalSolver
from data_generation.simulations.simulator import Simulator
from data_generation.simulations.grid import Grid, fractional_transformation, logistic_transformation

## General ODE Solver / FHN Model

In [ ]:
bounds = [(-np.inf, np.inf), (-np.inf, np.inf)]
resolution = [3, 3]
transformations = [logistic_transformation({'k': 1, 'x_0': 0}), logistic_transformation({'k': 1, 'x_0': 0})]
fhngrid = Grid(bounds, resolution, transformations)
model = FitzHughNagumoModel(control_params=['I'])
solver = GeneralODENumericalSolver(model)
fhnsimulator = Simulator(fhngrid, model, solver)

# Test parameters
delta_t = 0.1
num_steps = 2
num_samples_per_cell = 1
n_samples = num_samples_per_cell * resolution[0] * resolution[1]

In [47]:
scalar_control = np.array(0.5)
control_value = 0.5
array_control = np.array([control_value])
full_control = np.full((num_steps, n_samples, 1), control_value)
random_control = np.random.rand(num_steps, n_samples, 1)

a = fhnsimulator.create_control_array(scalar_control, num_steps, n_samples, fhnsimulator.control_dim)
b = fhnsimulator.create_control_array(array_control, num_steps, n_samples, fhnsimulator.control_dim)
c = fhnsimulator.create_control_array(full_control, num_steps, n_samples, fhnsimulator.control_dim)
d = fhnsimulator.create_control_array(random_control, num_steps, n_samples, fhnsimulator.control_dim)

In [48]:
a.shape, b.shape, c.shape, d.shape

((2, 9, 1), (2, 9, 1), (2, 9, 1), (2, 9, 1))

In [49]:
df1f = fhnsimulator.simulate(scalar_control, delta_t, num_samples_per_cell, num_steps)
df2f = fhnsimulator.simulate(array_control, delta_t, num_samples_per_cell, num_steps)
df3f = fhnsimulator.simulate(full_control, delta_t, num_samples_per_cell, num_steps)
df4f = fhnsimulator.simulate(random_control, delta_t, num_samples_per_cell, num_steps)

[[-2.24982991 -2.00910029]
 [-1.83322565  0.14222783]
 [-0.79995284  2.06520986]
 [ 0.64231538 -0.80216306]
 [ 0.02928139  0.21078484]
 [-0.16668517  1.28652602]
 [ 3.21066825 -1.80295408]
 [ 1.05399786  0.04923392]
 [ 1.20602196  1.61242232]]
Simulation complete:
- 9 samples × 2 timesteps = 18 total rows
- State dimensions: 2
- Control dimensions: 1
[[-1.42360761 -2.86978205]
 [-0.94077028  0.0236615 ]
 [-2.39017209  1.64834678]
 [ 0.02462496 -1.89791643]
 [ 0.33513611  0.11304717]
 [-0.14321464  1.98199194]
 [ 2.56136361 -1.97828078]
 [ 2.42343801 -0.60148921]
 [ 2.18074201  2.15777436]]
Simulation complete:
- 9 samples × 2 timesteps = 18 total rows
- State dimensions: 2
- Control dimensions: 1
[[-1.05242724 -0.98186052]
 [-1.40712246 -0.06720828]
 [-2.36947234  1.63166605]
 [ 0.27265526 -0.82999381]
 [ 0.32028744  0.17274616]
 [ 0.17534191  2.52836342]
 [ 1.70429074 -5.38058984]
 [ 0.9102832   0.18790787]
 [ 1.28939155  1.37262481]]
Simulation complete:
- 9 samples × 2 timesteps = 1

In [50]:
df1f

run_id trajectory_id   t0   t1        x0        x1   c0  \
0   20250207_160625         0-0_0  0.0  0.1 -2.249830 -1.833226  0.5   
1   20250207_160625         0-0_0  0.1  0.2 -1.908990 -1.781065  0.5   
2   20250207_160625         0-1_0  0.0  0.1 -0.799953  0.642315  0.5   
3   20250207_160625         0-1_0  0.1  0.2 -1.020604  0.831570  0.5   
4   20250207_160625         0-2_0  0.0  0.1  0.029281 -0.166685  0.5   
5   20250207_160625         0-2_0  0.1  0.2  0.062608 -0.265928  0.5   
6   20250207_160625         1-0_0  0.0  0.1  3.210668  1.053998  0.5   
7   20250207_160625         1-0_0  0.1  0.2  2.835697  1.163712  0.5   
8   20250207_160625         1-1_0  0.0  0.1  1.206022 -2.009100  0.5   
9   20250207_160625         1-1_0  0.1  0.2  1.158189 -1.994435  0.5   
10  20250207_160625         1-2_0  0.0  0.1  0.142228  2.065210  0.5   
11  20250207_160625         1-2_0  0.1  0.2  0.131626  2.037271  0.5   
12  20250207_160625         2-0_0  0.0  0.1 -0.802163  0.210785  0.5   
13  20250207_160625         2-0_0  0.1  0.2 -0.780541  0.214032  0.5   
14  20250207_160625         2-1_0  0.0  0.1  1.286526 -1.802954  0.5   
15  20250207_160625         2-1_0  0.1  0.2  1.274013 -1.750623  0.5   
16  20250207_160625         2-2_0  0.0  0.1  0.049234  1.612422  0.5   
17  20250207_160625         2-2_0  0.1  0.2  0.062990  1.606874  0.5   

          y0        y1  
0  -1.908990 -1.781065  
1  -1.650498 -1.738185  
2  -1.020604  0.831570  
3  -1.237344  1.024363  
4   0.062608 -0.265928  
5   0.099071 -0.373463  
6   2.835697  1.163712  
7   2.650566  1.268227  
8   1.158189 -1.994435  
9   1.112529 -1.977611  
10  0.131626  2.037271  
11  0.121534  2.007942  
12 -0.780541  0.214032  
13 -0.757672  0.217515  
14  1.274013 -1.750623  
15  1.260837 -1.701068  
16  0.062990  1.606874  
17  0.077424  1.601024

In [ ]:
model = FitzHughNagumoModel(control_params=['I', 'a'])
solver = GeneralODENumericalSolver(model)
fhnsimulator = Simulator(fhngrid, model, solver)

In [52]:
control_value1 = 0.7
control_value2 = 0.3
array_control = np.array([control_value1, control_value2])
full_control = np.concatenate((np.full((num_steps, n_samples, 1), control_value1), np.full((num_steps, n_samples, 1), control_value2)), axis=2)
random_control = np.random.rand(num_steps, n_samples, 2)

e = fhnsimulator.create_control_array(array_control, num_steps, n_samples, fhnsimulator.control_dim)
f = fhnsimulator.create_control_array(full_control, num_steps, n_samples, fhnsimulator.control_dim)
g = fhnsimulator.create_control_array(random_control, num_steps, n_samples, fhnsimulator.control_dim)

In [53]:
df5f = fhnsimulator.simulate(array_control, delta_t, num_samples_per_cell, num_steps)
df6f = fhnsimulator.simulate(full_control, delta_t, num_samples_per_cell, num_steps)
df7f = fhnsimulator.simulate(random_control, delta_t, num_samples_per_cell, num_steps)

[[-0.81106201 -1.38083451]
 [-1.40014376 -0.14306167]
 [-1.03617333  1.81286026]
 [ 0.50941602 -1.46996454]
 [-0.46490804 -0.67424991]
 [ 0.40366248  0.97785598]
 [ 1.32895259 -1.73352581]
 [ 1.82284498  0.53688999]
 [ 0.71537719  1.69771826]]
Simulation complete:
- 9 samples × 2 timesteps = 18 total rows
- State dimensions: 2
- Control dimensions: 2
[[-1.17201779 -0.80200063]
 [-3.89544301 -0.20631624]
 [-1.5678975   3.09624178]
 [ 0.67571048 -1.78941635]
 [ 0.54469789 -0.39701521]
 [ 0.1105736   1.43396867]
 [ 2.28816255 -1.30892397]
 [ 1.83919386 -0.47836004]
 [ 1.30692666  3.17413646]]
Simulation complete:
- 9 samples × 2 timesteps = 18 total rows
- State dimensions: 2
- Control dimensions: 2
[[-0.77911902 -0.77021762]
 [-1.63287508  0.54095633]
 [-1.81404602  0.90337788]
 [-0.31860704 -1.53834421]
 [-0.33286147 -0.05199084]
 [ 0.6674751   1.96078735]
 [ 1.06469987 -0.93179998]
 [ 2.06474916 -0.33529664]
 [ 4.34510687  1.62815959]]
Simulation complete:
- 9 samples × 2 timesteps = 1

In [54]:
df6f

run_id trajectory_id   t0   t1        x0        x1   c0   c1  \
0   20250207_160625         0-0_0  0.0  0.1 -1.172018 -3.895443  0.7  0.3   
1   20250207_160625         0-0_0  0.1  0.2 -1.086850 -2.893441  0.7  0.3   
2   20250207_160625         0-1_0  0.0  0.1 -1.567898  0.675710  0.7  0.3   
3   20250207_160625         0-1_0  0.1  0.2 -1.811544  0.986372  0.7  0.3   
4   20250207_160625         0-2_0  0.0  0.1  0.544698  0.110574  0.7  0.3   
5   20250207_160625         0-2_0  0.1  0.2  0.708051  0.045775  0.7  0.3   
6   20250207_160625         1-0_0  0.0  0.1  2.288163  1.839194  0.7  0.3   
7   20250207_160625         1-0_0  0.1  0.2  2.311252  1.921664  0.7  0.3   
8   20250207_160625         1-1_0  0.0  0.1  1.306927 -0.802001  0.7  0.3   
9   20250207_160625         1-1_0  0.1  0.2  1.122352 -0.798391  0.7  0.3   
10  20250207_160625         1-2_0  0.0  0.1 -0.206316  3.096242  0.7  0.3   
11  20250207_160625         1-2_0  0.1  0.2 -0.227637  3.045780  0.7  0.3   
12  20250207_160625         2-0_0  0.0  0.1 -1.789416 -0.397015  0.7  0.3   
13  20250207_160625         2-0_0  0.1  0.2 -1.757669 -0.384606  0.7  0.3   
14  20250207_160625         2-1_0  0.0  0.1  1.433969 -1.308924  0.7  0.3   
15  20250207_160625         2-1_0  0.1  0.2  1.418740 -1.271602  0.7  0.3   
16  20250207_160625         2-2_0  0.0  0.1 -0.478360  3.174136  0.7  0.3   
17  20250207_160625         2-2_0  0.1  0.2 -0.454928  3.145797  0.7  0.3   

          y0        y1  
0  -1.086850 -2.893441  
1  -1.003617 -2.455776  
2  -1.811544  0.986372  
3  -2.001424  1.294135  
4   0.708051  0.045775  
5   0.878320 -0.024200  
6   2.311252  1.921664  
7   2.323204  1.982682  
8   1.122352 -0.798391  
9   0.945518 -0.794159  
10 -0.227637  3.045780  
11 -0.243423  2.994234  
12 -1.757669 -0.384606  
13 -1.723854 -0.371027  
14  1.418740 -1.271602  
15  1.403169 -1.234619  
16 -0.454928  3.145797  
17 -0.431226  3.116387

## Technology Substitution

In [ ]:
bounds = [(0, np.inf), (0, np.inf)]
resolution = [3, 3]
transformations = [fractional_transformation(3.0), fractional_transformation(3.0)]
grid = Grid(bounds, resolution, transformations)
model = TechnologySubstitution()
solver = TechSubNumericalSolver(model)
simulator = Simulator(grid, model, solver)

# Test parameters
delta_t = 0.1
num_steps = 2
num_samples_per_cell = 1
n_samples = num_samples_per_cell * resolution[0] * resolution[1]

In [31]:
scalar_control = np.array(0.5)
control_value = 0.5
array_control = np.array([control_value])
full_control = np.full((num_steps, n_samples, 1), control_value)
random_control = np.random.rand(num_steps, n_samples, 1)

a = simulator.create_control_array(scalar_control, num_steps, n_samples, simulator.control_dim)
b = simulator.create_control_array(array_control, num_steps, n_samples, simulator.control_dim)
c = simulator.create_control_array(full_control, num_steps, n_samples, simulator.control_dim)
d = simulator.create_control_array(random_control, num_steps, n_samples, simulator.control_dim)

In [32]:
a.shape, b.shape, c.shape, d.shape

((2, 9, 1), (2, 9, 1), (2, 9, 1), (2, 9, 1))

In [33]:
df1 = simulator.simulate(scalar_control, delta_t, num_samples_per_cell, num_steps)
df2 = simulator.simulate(array_control, delta_t, num_samples_per_cell, num_steps)
df3 = simulator.simulate(full_control, delta_t, num_samples_per_cell, num_steps)
df4 = simulator.simulate(random_control, delta_t, num_samples_per_cell, num_steps)

Simulation complete:
- 9 samples × 2 timesteps = 18 total rows
- State dimensions: 2
- Control dimensions: 1
Simulation complete:
- 9 samples × 2 timesteps = 18 total rows
- State dimensions: 2
- Control dimensions: 1
Simulation complete:
- 9 samples × 2 timesteps = 18 total rows
- State dimensions: 2
- Control dimensions: 1
Simulation complete:
- 9 samples × 2 timesteps = 18 total rows
- State dimensions: 2
- Control dimensions: 1


In [34]:
df1

run_id trajectory_id   t0   t1           x0         x1   c0  \
0   20250203_170740         0-0_0  0.0  0.1     0.705174   0.401871  0.5   
1   20250203_170740         0-0_0  0.1  0.2     0.709102   0.435712  0.5   
2   20250203_170740         0-1_0  0.0  0.1     1.071769   3.134657  0.5   
3   20250203_170740         0-1_0  0.1  0.2     1.071921   3.208108  0.5   
4   20250203_170740         0-2_0  0.0  0.1     1.052110  28.171118  0.5   
5   20250203_170740         0-2_0  0.1  0.2     1.052110  28.261885  0.5   
6   20250203_170740         1-0_0  0.0  0.1     4.592137   0.135327  0.5   
7   20250203_170740         1-0_0  0.1  0.2     4.650146   0.135600  0.5   
8   20250203_170740         1-1_0  0.0  0.1     1.790398   3.465990  0.5   
9   20250203_170740         1-1_0  0.1  0.2     1.790832   3.540377  0.5   
10  20250203_170740         1-2_0  0.0  0.1     4.681904   9.512690  0.5   
11  20250203_170740         1-2_0  0.1  0.2     4.682345   9.596630  0.5   
12  20250203_170740         2-0_0  0.0  0.1   271.136255   0.634978  0.5   
13  20250203_170740         2-0_0  0.1  0.2   271.230256   0.634979  0.5   
14  20250203_170740         2-1_0  0.0  0.1    29.778087   2.138372  0.5   
15  20250203_170740         2-1_0  0.1  0.2    29.857125   2.141863  0.5   
16  20250203_170740         2-2_0  0.0  0.1  2106.832797  13.695969  0.5   
17  20250203_170740         2-2_0  0.1  0.2  2106.930617  13.695980  0.5   

             y0         y1  
0      0.709102   0.435712  
1      0.712566   0.471714  
2      1.071921   3.208108  
3      1.072066   3.281847  
4      1.052110  28.261885  
5      1.052111  28.352666  
6      4.650146   0.135600  
7      4.708387   0.135867  
8      1.790832   3.540377  
9      1.791246   3.615030  
10     4.682345   9.596630  
11     4.682777   9.680645  
12   271.230256   0.634979  
13   271.324258   0.634979  
14    29.857125   2.141863  
15    29.936192   2.145346  
16  2106.930617  13.695980  
17  2107.028438  13.695990

In [35]:
df4

run_id trajectory_id   t0   t1          x0         x1        c0  \
0   20250203_170740         0-0_0  0.0  0.1    0.290473   0.592808  0.113623   
1   20250203_170740         0-0_0  0.1  0.2    0.290474   0.678969  0.300966   
2   20250203_170740         0-1_0  0.0  0.1    0.486369   5.137818  0.379986   
3   20250203_170740         0-1_0  0.1  0.2    0.486371   5.221697  0.877800   
4   20250203_170740         0-2_0  0.0  0.1    0.128761   7.418061  0.137121   
5   20250203_170740         0-2_0  0.1  0.2    0.128761   7.512885  0.620249   
6   20250203_170740         1-0_0  0.0  0.1    5.051005   0.262545  0.122740   
7   20250203_170740         1-0_0  0.1  0.2    5.053522   0.338773  0.095330   
8   20250203_170740         1-1_0  0.0  0.1    1.679917   3.754976  0.768632   
9   20250203_170740         1-1_0  0.1  0.2    1.682100   3.816900  0.894837   
10  20250203_170740         1-2_0  0.0  0.1    5.370611  14.837946  0.295487   
11  20250203_170740         1-2_0  0.1  0.2    5.370627  14.930390  0.680549   
12  20250203_170740         2-0_0  0.0  0.1   35.191517   0.664714  0.223124   
13  20250203_170740         2-0_0  0.1  0.2   35.268617   0.671621  0.139038   
14  20250203_170740         2-1_0  0.0  0.1  262.575605   2.536387  0.058251   
15  20250203_170740         2-1_0  0.1  0.2  262.581916   2.626525  0.368006   
16  20250203_170740         2-2_0  0.0  0.1   11.869823  23.926355  0.955399   
17  20250203_170740         2-2_0  0.1  0.2   11.879709  23.998200  0.911837   

            y0         y1  
0     0.290474   0.678969  
1     0.290491   0.746023  
2     0.486371   5.221697  
3     0.486459   5.286496  
4     0.128761   7.512885  
5     0.128762   7.591382  
6     5.053522   0.338773  
7     5.053956   0.423378  
8     1.682100   3.816900  
9     1.686137   3.872308  
10    5.370627  14.930390  
11    5.371552  15.012555  
12   35.268617   0.671621  
13   35.310688   0.715393  
14  262.581916   2.626525  
15  262.675685   2.626664  
16   11.879709  23.998200  
17   11.887772  24.072606